version: 2.1

jobs:
  ok-to-continue:
    type: no-op
  deploy:
    docker:
      - image: cimg/base:current

    steps:
      - run:
          name: "Deploy"
          command: echo "Hello!"

workflows:
  workflow:
    jobs:
      - hold:
        type: approval
      - deploy:
          requires:
            - hold
