version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current

    steps:
      - run:
          name: "Deploy"
          command: echo "Hello!"

workflows:
  workflow:
    jobs:
      - ok-to-continue:
          type: no-op
      - deploy:
          requires:
            - ok-to-continue: failed
